# Site settings
title: Chris Kihlstrom On Code
header-img: img/home-bg.png
email: ckihlst@gmail.com
copyright_name: chriskihlstrom
description: > # this means to ignore newlines until "baseurl:"
  Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: chriskihlstrom
github_username:  chriskihlstrom
learn_profile: chriskihlstrom
email_username: ckihlst@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
